# Generated by Django 4.2.22 on 2025-06-17 10:00

import customer.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('customer_name', models.CharField(max_length=50)),
                ('tax_number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('mobile', models.BigIntegerField(blank=True, db_index=True, null=True)),
                ('point', models.FloatField(blank=True, default=0, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=customer.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=customer.models.initial_sync_online, null=True)),
            ],
        ),
    ]
