# Generated by Django 4.2.22 on 2026-01-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='last_visit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
