# Generated by Django 4.2.22 on 2026-01-20 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_last_visit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sms_alert',
            field=models.DateField(blank=True, null=True),
        ),
    ]
