# Generated by Django 4.2.22 on 2026-04-01 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_customer_sms_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='blocked_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='blocked_reason',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='is_blocked',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
