# Generated by Django 4.2.22 on 2026-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_blocked_date_customer_blocked_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='blocked_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
