# Generated by Django 4.2.17 on 2025-05-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerpointlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerPointLog',
        ),
    ]
