# Generated by Django 4.2.22 on 2026-08-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_blocked_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='sms_notification',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
