# Generated by Django 4.2.22 on 2026-08-10 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_customer_sms_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sms_notification',
            field=models.BooleanField(blank=True, db_index=True, default=True, null=True),
        ),
    ]
