# Generated by Django 4.2.17 on 2025-03-07 06:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('staff_name', models.CharField(max_length=50)),
                ('join_date', models.DateField(blank=True, default=None, null=True)),
                ('exit_date', models.DateField(blank=True, default=None, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('country', models.CharField(blank=True, max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=10, null=True)),
                ('mobile', models.IntegerField(default=None, null=True)),
                ('remark', models.CharField(blank=True, max_length=200, null=True)),
                ('salary', models.FloatField(default=None, null=True)),
                ('id_number', models.CharField(blank=True, max_length=50, null=True)),
                ('discontinued', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance_Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('date', models.DateField(blank=True, default=None, null=True)),
                ('in_time', models.IntegerField(blank=True, default=None, null=True)),
                ('out_time', models.IntegerField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
            options={
                'unique_together': {('company', 'date', 'staff')},
            },
        ),
    ]
