# Generated by Django 4.2.20 on 2025-05-12 18:02

from django.db import migrations, models
import django.db.models.deletion
import staff.models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_address_alter_staff_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(default=staff.models.current_time)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.staff')),
            ],
        ),
    ]
