# Generated by Django 4.2.20 on 2025-05-12 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_credit'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credit',
            new_name='Staff_Credit',
        ),
    ]
