# Generated by Django 4.2.20 on 2025-05-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_credit_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='id_number',
        ),
        migrations.AddField(
            model_name='staff',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='epf_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='esi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
