# Generated by Django 4.2.22 on 2025-06-17 10:00

from django.db import migrations, models
import sync.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Record',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_id', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted', models.IntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=sync.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=sync.models.initial_sync_online, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='deleted_record',
            constraint=models.UniqueConstraint(fields=('model_name', 'model_id'), name='unique_model_entry'),
        ),
    ]
