# Generated by Django 4.2.17 on 2025-03-07 06:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('app_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(blank=True, max_length=100, null=True)),
                ('model_id', models.IntegerField(blank=True, null=True)),
                ('deleted', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
