# Generated by Django 4.2.22 on 2025-06-17 10:00

import bank.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('purchase', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_Account',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_name', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ac_type', models.CharField(blank=True, max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=50, null=True)),
                ('ifsc', models.CharField(blank=True, max_length=50, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=bank.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=bank.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Bank_Statement',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tran_id', models.CharField(blank=True, max_length=50, null=True)),
                ('entry_date', models.DateField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=50, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('debit', models.FloatField(blank=True, null=True)),
                ('credit', models.FloatField(blank=True, null=True)),
                ('balance', models.FloatField(blank=True, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=bank.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=bank.models.initial_sync_online, null=True)),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bank.bank_account')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='company.company')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.payment')),
            ],
            options={
                'unique_together': {('company', 'bank_account', 'tran_id', 'entry_date', 'balance')},
            },
        ),
    ]
