# Generated by Django 4.2.22 on 2025-06-17 10:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import expenses.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sync_offline', models.BigIntegerField(blank=True, default=expenses.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=expenses.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Flow_Expenses',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sync_offline', models.BigIntegerField(blank=True, default=expenses.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=expenses.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
