# Generated by Django 4.2.22 on 2025-10-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cash_Flow_Expenses',
        ),
    ]
