# Generated by Django 4.2.17 on 2025-03-07 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tax_code', '0001_initial'),
        ('company', '0001_initial'),
        ('supplier', '0001_initial'),
        ('inventory', '0001_initial'),
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=25, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('round_off', models.FloatField(blank=True, default=0, null=True)),
                ('other_charges', models.FloatField(blank=True, default=0, null=True)),
                ('payable_amount', models.FloatField(blank=True, default=0, null=True)),
                ('finish', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_only', models.IntegerField(blank=True, default=0, null=True)),
                ('total_margin', models.FloatField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('barcode', models.IntegerField(default=0, unique=True)),
                ('pre_barcode', models.CharField(blank=True, max_length=50, null=True)),
                ('tax_rate', models.FloatField(default=0)),
                ('buy_price', models.FloatField(default=0)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('unit', models.FloatField(default=0)),
                ('qty', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('mrp', models.FloatField(default=0)),
                ('sold', models.FloatField(blank=True, default=0, null=True)),
                ('mfg_date', models.DateField(blank=True, default=None, null=True)),
                ('exp_date', models.DateField(blank=True, default=None, null=True)),
                ('best_before', models.CharField(blank=True, max_length=5, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('tax_code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_code.tax_code')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
                ('purchase', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase')),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='purchase.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('sticker_name', models.CharField(blank=True, max_length=50, null=True)),
                ('column', models.IntegerField(blank=True, default=0, null=True)),
                ('sticker_code', models.TextField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('entry_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
                ('paid_by', models.CharField(blank=True, max_length=15, null=True)),
                ('tran_no', models.CharField(blank=True, max_length=100, null=True)),
                ('cheque_cleared', models.IntegerField(blank=True, default=0, null=True)),
                ('cheque_given', models.IntegerField(blank=True, default=0, null=True)),
                ('bank_checked', models.IntegerField(blank=True, default=0, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purchase.purchase')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
