# Generated by Django 4.2.22 on 2025-06-20 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='imported_stock',
            field=models.BooleanField(default=False),
        ),
    ]
