# Generated by Django 4.2.17 on 2025-03-20 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['barcode'], name='purchase_st_barcode_4e9988_idx'),
        ),
    ]
