# Generated by Django 4.2.17 on 2025-03-20 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_stock_purchase_st_barcode_4e9988_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['pre_barcode'], name='purchase_st_pre_bar_903ab1_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['company'], name='purchase_st_company_989135_idx'),
        ),
    ]
