# Generated by Django 4.2.22 on 2026-09-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_stock_imported_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='stock_maintenance',
            field=models.BooleanField(default=False),
        ),
    ]
