# Generated by Django 4.2.17 on 2025-04-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_stock_purchase_st_pre_bar_903ab1_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='best_before',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pre_barcode',
            field=models.CharField(blank=True, max_length=550, null=True),
        ),
    ]
