# Generated by Django 4.2.20 on 2025-04-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_stock_best_before_alter_stock_pre_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='sticker',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
