# Generated by Django 4.2.17 on 2025-04-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_stock_sticker'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='verify',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
