# Generated by Django 4.2.17 on 2025-04-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_purchase_verify'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='verify',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
