# Generated by Django 4.2.17 on 2025-04-25 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0007_payment_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='purchase.purchase'),
        ),
    ]
