# Generated by Django 4.2.17 on 2025-05-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0008_alter_stock_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='purchase_scans/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='purchase.purchase')),
            ],
        ),
    ]
