# Generated by Django 4.2.17 on 2025-05-04 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0009_purchasescan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchasescan',
            name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='purchasescan',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.purchase'),
        ),
    ]
