# Generated by Django 4.2.17 on 2025-05-04 13:26

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0010_remove_purchasescan_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasescan',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 5, 4, 18, 56, 42, 184815)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='purchasescan',
            name='purchase',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='purchase.purchase'),
        ),
    ]
