# Generated by Django 4.2.17 on 2025-05-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0011_purchasescan_uploaded_at_alter_purchasescan_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='finish_upload',
            field=models.BooleanField(default=False),
        ),
    ]
