# Generated by Django 4.2.17 on 2025-05-07 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0012_purchase_finish_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
