# Generated by Django 4.2.17 on 2025-05-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0013_alter_payment_transaction_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='transaction_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
