# Generated by Django 4.2.22 on 2025-06-17 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import todo.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('task_date', models.DateField(null=True)),
                ('finish_date', models.DateField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=todo.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=todo.models.initial_sync_online, null=True)),
                ('task_type', models.IntegerField(blank=True, choices=[(0, 'General'), (1, 'Urgent'), (2, 'Immediate')], default=0, null=True)),
                ('task_repeat', models.IntegerField(blank=True, choices=[(0, 'One Time'), (1, 'Every Day'), (2, 'Every Week'), (3, 'Every Month'), (4, 'Every Year')], default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
