# Generated by Django 4.2.17 on 2025-03-07 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('task_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('task_date', models.DateField(null=True)),
                ('finish_date', models.DateField(null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('task_type', models.IntegerField(choices=[(0, 'General'), (1, 'Urgent'), (2, 'Immediate')], default=0, null=True)),
                ('task_repeat', models.IntegerField(choices=[(0, 'One Time'), (1, 'Every Day'), (2, 'Every Week'), (3, 'Every Month'), (4, 'Every Year')], default=0, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
