# Generated by Django 4.2.17 on 2025-05-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='finish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_repeat',
            field=models.IntegerField(blank=True, choices=[(0, 'One Time'), (1, 'Every Day'), (2, 'Every Week'), (3, 'Every Month'), (4, 'Every Year')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_type',
            field=models.IntegerField(blank=True, choices=[(0, 'General'), (1, 'Urgent'), (2, 'Immediate')], default=0, null=True),
        ),
    ]
