# Generated by Django 4.2.22 on 2025-06-17 10:00

from django.db import migrations, models
import django.db.models.deletion
import inventory.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('tax_code', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('sync_offline', models.BigIntegerField(blank=True, default=inventory.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=inventory.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('inventory_name', models.CharField(max_length=200)),
                ('shortcode', models.CharField(blank=True, max_length=10, null=True)),
                ('unit_enabled', models.IntegerField(default=0)),
                ('default_price', models.IntegerField(blank=True, default=None, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=inventory.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=inventory.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('tax_rate', models.FloatField()),
                ('trigger_amount', models.FloatField()),
                ('sync_offline', models.BigIntegerField(blank=True, default=inventory.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=inventory.models.initial_sync_online, null=True)),
                ('inventories', models.ManyToManyField(related_name='tax_slabs', to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('sync_offline', models.BigIntegerField(blank=True, default=inventory.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=inventory.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.floor')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.section'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='tax_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tax_code.tax_code'),
        ),
        migrations.AlterUniqueTogether(
            name='inventory',
            unique_together={('company', 'inventory_name', 'tax_code')},
        ),
    ]
