# Generated by Django 4.2.22 on 2025-10-11 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='company',
        ),
        migrations.RemoveField(
            model_name='section',
            name='floor',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='section',
        ),
        migrations.DeleteModel(
            name='Floor',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
