# Generated by Django 4.2.22 on 2026-07-21 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_section_company_remove_section_floor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='default_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
