# Generated by Django 4.2.17 on 2025-05-04 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_floor_section_inventory_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaxSlab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tax_rate', models.FloatField(help_text='Tax percentage to apply when slab triggers')),
                ('trigger_amount', models.FloatField(help_text='Apply slab if sale amount exceeds this')),
                ('inventories', models.ManyToManyField(related_name='tax_slabs', to='inventory.inventory')),
            ],
        ),
    ]
