# Generated by Django 4.2.17 on 2025-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_taxslab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxslab',
            name='tax_rate',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='taxslab',
            name='trigger_amount',
            field=models.FloatField(),
        ),
    ]
