# Generated by Django 4.2.21 on 2025-05-22 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pos_statement_restriction',
            field=models.BooleanField(default=False),
        ),
    ]
