# Generated by Django 4.2.22 on 2025-06-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='print_qrcode',
            field=models.BooleanField(default=True),
        ),
    ]
