# Generated by Django 4.2.22 on 2025-06-25 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_print_qrcode'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivity',
        ),
    ]
