# Generated by Django 4.2.22 on 2025-06-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_useractivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online_db_readonly',
            field=models.BooleanField(default=True),
        ),
    ]
