# Generated by Django 4.2.22 on 2025-07-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_user_online_db_readonly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.IntegerField(choices=[(0, 'Super Admin'), (2, 'Billing'), (4, 'Purchase Entry'), (3, 'Customer Care'), (5, 'Auditor'), (1, 'Administrator')], default=0, null=True),
        ),
    ]
