# Generated by Django 4.2.22 on 2025-10-11 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='browser_access',
            field=models.BooleanField(default=False),
        ),
    ]
