# Generated by Django 4.2.17 on 2025-05-20 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('purchase', '0015_columnpreference'),
        ('company', '0004_alter_company_mobile'),
        ('inventory', '0005_alter_taxslab_tax_rate_alter_taxslab_trigger_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Print_Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=150, null=True)),
                ('template', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnprintedSaleLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('unit', models.FloatField(default=0)),
                ('qty', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible_duration', models.IntegerField(default=0, help_text='Duration in milliseconds the row was visible before print or refresh.')),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('row_number', models.IntegerField()),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('stand_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_taken', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('finish', models.IntegerField(blank=True, default=0, null=True)),
                ('shortage', models.FloatField(blank=True, default=None, null=True)),
                ('stand_by_total', models.FloatField(blank=True, default=None, null=True)),
                ('cash_taken_total', models.FloatField(blank=True, default=None, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
