# Generated by Django 4.2.22 on 2025-06-17 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pos.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
        ('purchase', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Print_Template',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('template_name', models.CharField(blank=True, max_length=150, null=True)),
                ('template', models.TextField(blank=True, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=pos.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=pos.models.initial_sync_online, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnprintedSaleLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=100)),
                ('row_number', models.IntegerField(blank=True, null=True)),
                ('unit', models.FloatField(default=0)),
                ('qty', models.FloatField(default=0)),
                ('sale_price', models.FloatField(default=0)),
                ('discount', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visible_duration', models.IntegerField(default=0, help_text='Duration in milliseconds the row was visible before print or refresh.')),
                ('sync_offline', models.BigIntegerField(blank=True, default=pos.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=pos.models.initial_sync_online, null=True)),
                ('inventory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.inventory')),
                ('stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='purchase.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FieldChangeLog',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('row_number', models.IntegerField()),
                ('field', models.CharField(max_length=50)),
                ('old_value', models.CharField(blank=True, max_length=255, null=True)),
                ('new_value', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=pos.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=pos.models.initial_sync_online, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cash_Counter',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('stand_by', models.CharField(blank=True, max_length=100, null=True)),
                ('cash_taken', models.CharField(blank=True, max_length=100, null=True)),
                ('entry_date', models.DateTimeField(blank=True, null=True)),
                ('finish', models.IntegerField(blank=True, default=0, null=True)),
                ('shortage', models.FloatField(blank=True, default=None, null=True)),
                ('stand_by_total', models.FloatField(blank=True, default=None, null=True)),
                ('cash_taken_total', models.FloatField(blank=True, default=None, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=pos.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=pos.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
