# Generated by Django 4.2.22 on 2025-06-19 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unprintedsalelog',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='unprintedsalelog',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='unprintedsalelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='FieldChangeLog',
        ),
        migrations.DeleteModel(
            name='UnprintedSaleLog',
        ),
    ]
