# Generated by Django 4.2.22 on 2025-06-17 10:00

from django.db import migrations, models
import django.db.models.deletion
import tax_code.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax_Code',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('tax_code', models.IntegerField(default=0, null=True)),
                ('tax_rate', models.IntegerField(default=0, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=tax_code.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=tax_code.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'unique_together': {('company', 'tax_code')},
            },
        ),
    ]
