# Generated by Django 4.2.22 on 2025-06-17 10:00

import company.models
from django.db import migrations, models
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('company_name', models.CharField(max_length=150, null=True)),
                ('tax_number', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=200, null=True)),
                ('tax_type', models.CharField(choices=[('Gst', 'GST'), ('Vat', 'VAT')], max_length=10, null=True)),
                ('mobile', models.BigIntegerField(default=None, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=company.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=company.models.initial_sync_online, null=True)),
            ],
        ),
    ]
