# Generated by Django 4.2.17 on 2025-04-21 07:14

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='country',
            field=django_countries.fields.CountryField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_type',
            field=models.CharField(choices=[('Gst', 'GST'), ('Vat', 'VAT')], max_length=10, null=True),
        ),
    ]
