# Generated by Django 4.2.20 on 2025-04-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='mobile',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
