# Generated by Django 4.2.22 on 2025-06-17 10:00

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import supplier.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('supplier_name', models.CharField(max_length=150)),
                ('tax_number', models.CharField(max_length=150, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=200, null=True)),
                ('country', django_countries.fields.CountryField(max_length=200, null=True)),
                ('pincode', models.CharField(max_length=200, null=True)),
                ('mobile', models.BigIntegerField(default=None, null=True)),
                ('code_name', models.CharField(blank=True, max_length=20, null=True)),
                ('default_margin', models.CharField(blank=True, max_length=20, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=supplier.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=supplier.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('entry_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('qty', models.IntegerField(blank=True, default=0, null=True)),
                ('transport', models.CharField(blank=True, max_length=50, null=True)),
                ('transport_charge', models.FloatField(blank=True, default=0, null=True)),
                ('service_charge', models.FloatField(blank=True, default=0, null=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=supplier.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=supplier.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
