# Generated by Django 4.2.17 on 2025-04-24 13:32

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=django_countries.fields.CountryField(max_length=200, null=True),
        ),
    ]
