# Generated by Django 4.2.20 on 2025-04-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='mobile',
            field=models.BigIntegerField(default=None, null=True),
        ),
    ]
