# Generated by Django 4.2.17 on 2025-05-08 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0004_alter_supplier_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='default_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
