# Generated by Django 4.2.17 on 2025-05-08 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0005_supplier_default_margin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='default_margin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
