# Generated by Django 4.2.22 on 2025-06-17 10:00

from django.db import migrations, models
import django.db.models.deletion
import setting.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Master_Setting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('setting', models.CharField(max_length=50, unique=True)),
                ('value', models.CharField(max_length=100)),
                ('sync_offline', models.BigIntegerField(blank=True, default=setting.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=setting.models.initial_sync_online, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('setting', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=1000)),
                ('sync_offline', models.BigIntegerField(blank=True, default=setting.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=setting.models.initial_sync_online, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'setting'), name='unique_company_setting'),
        ),
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together={('company', 'setting')},
        ),
    ]
