# Generated by Django 4.2.17 on 2025-04-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(condition=models.Q(('company__isnull', False)), fields=('company', 'setting'), name='unique_company_setting'),
        ),
    ]
