# Generated by Django 4.2.22 on 2025-07-06 09:11

from django.db import migrations, models
import setting.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_name', models.CharField(max_length=500)),
                ('directory_name', models.CharField(max_length=500)),
                ('uploaded_to_s3', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=setting.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=setting.models.initial_sync_online, null=True)),
            ],
        ),
    ]
