# Generated by Django 4.2.22 on 2025-07-06 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
