# Generated by Django 4.2.22 on 2026-09-29 14:17

import automation.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_alter_inventory_default_price'),
        ('attribute', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Order_Setting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('minimum_stock', models.FloatField(default=0)),
                ('maximum_stock', models.FloatField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=automation.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=automation.models.initial_sync_online, null=True)),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.CreateModel(
            name='Stock_Order_Setting_Attribute',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sync_offline', models.BigIntegerField(blank=True, default=automation.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=automation.models.initial_sync_online, null=True)),
                ('attribute', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
                ('stock_order_setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='automation.stock_order_setting')),
            ],
        ),
    ]
