# Generated by Django 4.2.22 on 2026-09-30 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_order_setting',
            name='default_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_order_settings', to='supplier.supplier'),
        ),
        migrations.AddField(
            model_name='stock_order_setting',
            name='minimum_order_qty',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
