# Generated by Django 4.2.22 on 2026-09-30 09:20

import automation.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0001_initial'),
        ('supplier', '0001_initial'),
        ('inventory', '0003_alter_inventory_default_price'),
        ('automation', '0002_stock_order_setting_default_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock_order_setting',
            name='default_supplier',
        ),
        migrations.RemoveField(
            model_name='stock_order_setting',
            name='minimum_order_qty',
        ),
        migrations.CreateModel(
            name='Stock_Order_Brand_Setting',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whatsapp_mobile', models.CharField(blank=True, max_length=20, null=True)),
                ('minimum_order_qty', models.FloatField(default=0)),
                ('enabled', models.BooleanField(default=True)),
                ('sync_offline', models.BigIntegerField(blank=True, default=automation.models.initial_sync_offline, null=True)),
                ('sync_online', models.BigIntegerField(blank=True, default=automation.models.initial_sync_online, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attribute.attribute')),
                ('default_supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supplier.supplier')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.inventory')),
            ],
        ),
        migrations.AddConstraint(
            model_name='stock_order_brand_setting',
            constraint=models.UniqueConstraint(fields=('inventory', 'brand'), name='unique_stock_order_brand_setting'),
        ),
    ]
