# Generated by Django 4.2.22 on 2026-09-30 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_remove_stock_order_setting_default_supplier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_order_brand_setting',
            name='per_box_contain',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
