# Generated by Django 4.2.22 on 2026-09-30 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_stock_order_brand_setting_per_box_contain'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock_order_setting',
            name='per_box_contain',
            field=models.PositiveIntegerField(blank=True, default=None, null=True),
        ),
    ]
