# Generated by Django 4.2.22 on 2026-09-30 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('automation', '0005_stock_order_setting_per_box_contain'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockOrderWhatsAppLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_mobile', models.CharField(max_length=20)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_items', models.JSONField(blank=True, default=list)),
                ('last_message', models.TextField(blank=True, default='')),
                ('status', models.CharField(blank=True, default='', max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplier.supplier')),
            ],
            options={
                'unique_together': {('supplier', 'whatsapp_mobile')},
            },
        ),
    ]
