# Generated by Django 4.2.22 on 2026-09-30 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_stockorderwhatsapplog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock_Order_WhatsApp_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField()),
                ('whatsapp_mobile', models.CharField(max_length=20)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_items', models.JSONField(blank=True, default=list)),
                ('last_message', models.TextField(blank=True, default='')),
            ],
            options={
                'unique_together': {('supplier_id', 'whatsapp_mobile')},
            },
        ),
        migrations.DeleteModel(
            name='StockOrderWhatsAppLog',
        ),
    ]
