# Generated by Django 4.2.22 on 2026-09-30 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
        ('automation', '0008_stock_order_whatsapp_log_list_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock_Order_WhatsApp_Log_list',
            new_name='Stock_Order_WhatsApp_Log',
        ),
    ]
