# Generated by Django 4.2.22 on 2026-04-02 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        ('invoice', '0002_manual_migrate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='staff.staff'),
        ),
    ]
