# Generated by Django 4.2.17 on 2025-03-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_invoice_invoice_inv_company_29475d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_inv_company_29475d_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_inv_invoice_54f3c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_inv_company_7d4bf5_idx',
        ),
    ]
