# Generated by Django 4.2.17 on 2025-03-11 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_remove_invoice_invoice_inv_company_29475d_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company'], name='invoice_inv_company_29475d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoice_inv_invoice_54f3c0_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company', 'invoice_date'], name='invoice_inv_company_7d4bf5_idx'),
        ),
    ]
