# Generated by Django 4.2.17 on 2025-04-02 12:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_invoice_invoice_inv_company_29475d_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_inv_company_29475d_idx',
        ),
        migrations.RemoveIndex(
            model_name='invoice',
            name='invoice_inv_invoice_54f3c0_idx',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(blank=True, db_index=True, default=0, null=True),
        ),
    ]
