# Generated by Django 4.2.17 on 2025-04-02 12:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_remove_invoice_invoice_inv_company_29475d_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['company'], name='invoice_inv_company_29475d_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['invoice_date'], name='invoice_inv_invoice_54f3c0_idx'),
        ),
    ]
