# Generated by Django 4.2.20 on 2025-05-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_alter_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='actual_sale_price',
            field=models.FloatField(default=0),
        ),
    ]
